disabled_rules:
  - private_over_fileprivate
  - cyclomatic_complexity
  - function_body_length
  - redundant_string_enum_value
  - todo
  - mark
#  - colon
#  - comma
#  - control_statement

opt_in_rules:
  - yoda_condition
  - xct_specific_matcher
  - weak_delegate
  - untyped_error_in_catch
#  - unused_import
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - toggle_bool
  - operator_usage_whitespace
  - nslocalizedstring_key
# - no_grouping_extension
# - number_separator
# - missing_docs
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
# - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
# - legacy_objc_type
  - identical_operands
  - function_default_parameter_at_end
  - force_unwrapping
  - flatmap_over_map_reduce
  - file_name_no_space
  - fatal_error_message
  - fallthrough
  - explicit_enum_raw_value
  - explicit_init
  - empty_xctest_method
  - empty_count
  - empty_string
  - empty_collection_literal
  - discouraged_object_literal
  - convenience_type
  - comma_inheritance
  - collection_alignment
  - closure_spacing
  - attributes
  - array_init
  - indentation_width
  - redundant_set_access_control
  - lower_acl_than_parent
  - explicit_acl

#included:
#excluded:

#analyzer_rules:
analyzer_rules:
  - unused_import

force_cast: warning
force_try: warning

line_length:
   warning: 120
   error: 200
   ignores_urls: false 
   ignores_function_declarations: false
   ignores_comments: false
   ignores_interpolated_strings: false

type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  - 700
  - 1200

type_name:
  min_length: 4
  max_length:
    - 40
    - 50
  excluded: iPhone
  allowed_symbols: ["_"]
identifier_name:
  min_length:
    - 2
  excluded:
    - API_KEY

indentation_width:
  severity: warning
  indentation_width: 2
  include_comments: true
  include_compiler_directives: true
  include_multiline_strings: true

reporter: "xcode"

nesting:
  type_level:
    - 4
    - 5
  function_level: 2
