excluded:
  - Carthage
  - .git
  - .build

opt_in_rules:
  - force_unwrapping
  - indentation_width
  - sorted_imports
  # - missing_docs
  - convenience_type
  - multiline_parameters
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - explicit_init
  - explicit_acl

disabled_rules:
  - trailing_comma
  - redundant_string_enum_value
  - nesting

force_cast: warning
force_try: warning

identifier_name:
  max_length:
    warning: 60
    error: 80

type_name:
  allowed_symbols: ["_"]

opening_brace:
  ignore_multiline_statement_conditions: true
  ignore_multiline_type_headers: true
  ignore_multiline_function_signatures: true

indentation_width:
  indentation_width: 2

reporter: "xcode"
